version: '2'
services:
  restyaboard:
    build: .
    ports:
      - 1234:80
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=restyaboard
      #- SMTP_SERVER=smtp_relay
      #- SMTP_PORT=587
      - TZ=Etc/UTC
    depends_on:
      - postgres
    restart: always

  # See https://hub.docker.com/r/boky/postfix for documentation
  # or try https://github.com/WeAreGenki/docker-smtp
  smtp_relay:
    image: boky/postfix
    environment:
      - RELAYHOST=fakesmtp2:25
      - ALLOW_EMPTY_SENDER_DOMAINS=true

  # Check messages at localhost:1080
  fakesmtp2:
    image: tophfr/mailcatcher
    ports:
      #- "1025:25"
      - "1080:80"

  postgres:
    image: postgres:9-alpine
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=restyaboard
    restart: always
